spring:
  datasource:
    url: jdbc:mysql://localhost:3306/job_system
    username: root
    password: your_password

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: localhost
      port: 6379